"""Group model

Revision ID: 37ed8ff89866
Revises: eb67bd74514c
Create Date: 2023-06-23 11:10:53.522219

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "37ed8ff89866"
down_revision = "eb67bd74514c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("permissions", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_groups_id"), "groups", ["id"], unique=False)
    op.add_column("users", sa.Column("group_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "users", "groups", ["group_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "group_id")
    op.drop_index(op.f("ix_groups_id"), table_name="groups")
    op.drop_table("groups")
    # ### end Alembic commands ###
