"""ThreatCategory model

Revision ID: 4027e2716666
Revises: b129dff1c4af
Create Date: 2023-06-22 14:56:03.866628

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "4027e2716666"
down_revision = "b129dff1c4af"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "threat_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_threat_categories_id"),
        "threat_categories",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threat_categories_id"), table_name="threat_categories")
    op.drop_table("threat_categories")
    # ### end Alembic commands ###
