"""test

Revision ID: 6050cbd05813
Revises: cf0c775dd340
Create Date: 2023-06-22 12:04:09.534192

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "6050cbd05813"
down_revision = "cf0c775dd340"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "disabled",
        existing_type=sa.BOOLEAN(),
        nullable=False,
    )
    op.alter_column(
        "users",
        "profile_image",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "profile_image",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "users",
        "disabled",
        existing_type=sa.BOOLEAN(),
        nullable=True,
    )
    op.alter_column(
        "users",
        "last_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "users",
        "first_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "users",
        "hashed_password",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.alter_column(
        "users",
        "email",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###
