"""User timestamped fields

Revision ID: a6f02fdda64b
Revises: 6050cbd05813
Create Date: 2023-06-22 12:41:48.242724

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a6f02fdda64b"
down_revision = "6050cbd05813"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_at", sa.DateTime(), nullable=False))
    op.add_column("users", sa.Column("updated_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###
