"""relationship between Post and Threat

Revision ID: be3282935a80
Revises: 8af9f78a681f
Create Date: 2023-06-23 10:52:46.969691

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "be3282935a80"
down_revision = "8af9f78a681f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("posts", sa.Column("threat_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "posts", "threats", ["threat_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "posts", type_="foreignkey")
    op.drop_column("posts", "threat_id")
    # ### end Alembic commands ###
