"""profile_image nullable added

Revision ID: fb44792d462f
Revises: 37ed8ff89866
Create Date: 2023-06-23 15:58:30.458249

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fb44792d462f"
down_revision = "37ed8ff89866"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "profile_image",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    op.drop_column("users", "permissions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("permissions", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "users",
        "profile_image",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
